version: "3"
 services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumns:
      - /xxx:/usr/share/nginx/html
    - /confxxx:/etc/nginx/nginx.conf
  jdk:
    image: imagename
    ports: 1080:1080
    volumns:
    - /outside:/inside
  mysql:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=123456